### ISSUE TITLE
state of all cover sensors resets at 2am

### ISSUE THREAD

**Issue by smokeyx** [sillyfrog/Automate-Pulse-v2#8] opened 2022-06-01 21:39 UTC
I just installed this integration a couple of weeks ago when I started installing my automated window coverings.  

I have the Pulse 2 hub running v2.7 (2) according to the Pulse 2 iOS app and via the Pulse Linq app when I run the Hub Firmware query it returns back "!000FWV010205".

I'm running Home Assistant Core 2022.6.0 and Home Assistant Supervisor 2022.05.3

The issue that I'm having is at 2am every morning (actually at 01:59:51) all of my cover sensors go "unavailable" then about 10 seconds later all of the covers sensors come back on reporting their batter level and open/closed state correctly, then immediately the covers that are actually closed report as opened.  (I've screen shot the entries from my logbook below)

This leaves all of the controls for these entities unless since they are in the open state but are actually closed.

Thanks!

![image](https://user-images.githubusercontent.com/5403335/171505837-02cd40e8-aeda-42cc-a7e9-f26fff24d899.png)

**Comment by sumur1au** [comment] 2022-07-06 22:50
Hi, I have already similar thing happen to all my devices at 3am, I am using the HomeKit integration, so that may indicate something at the firmware level of the hubs. They are all running V1.4.0

**Comment by wifihax** [comment] 2022-07-07 01:27
Mine exhibited this behaviour 5 times overnight. V1.4.0 on my hub. Blinds are entirely unresponsive to either hass or pulse 2 app this morning. A couple of weeks ago my blinds were actually entirely unpaired from the hub. 

I can see TLS traffic between AWS and my hub but I had to manually open the blinds today. 

It's unclear if this daily unresponsive in the early hours thing is an integration issue or whether the hub is going through some daily cycle, the latter is my guess so far.

**Comment by sumur1au** [comment] 2022-07-07 09:10
I contacted Acmeda tech support, they are aware of the problem and working on a new firmware to address the issue. I will let you know if you I get an email from the tech support team.

**Comment by smokeyx** [comment] 2022-07-09 17:13
Ironically, after upgrading to V1.4.0 I had about 2 weeks of no issues at all up until a few days ago when I lost connectivity overnight.  A power cycle on the hub fixed it but then yesterday morning I lost all connectivity and a power cycle didn't help so I had to factory reset the hub and re-pair all of my covers.

After spending nearly 2 hours over the course of several calls to their support I have very little faith that they will be able to get it under control any time soon.  They were very defensive each time I spoke with them and blamed all issues on Apple, Google and my internet connectivity despite me not using the google integration or Apple HomeKit and having stellar internet connectivity.

[sigh]

**Comment by sillyfrog** [comment] 2022-07-10 06:08
Sorry for the delay, I'm just starting to look at this. I have just updated to the latest stable HASS, so will see if I can repeat here. Hopefully it's not a bug in the hub (which it's sounding like).

I have automatons on all my blinds (set to follow the sun as it comes through the window), so wouldn't have noticed as the position is always updated through code. But I have removed one blind from that and will keep an eye on it. 

My HomeKit integration (straight to the hub, not using HA) I noticed has also lost the room they were in and all gone back to "default room". So something's clearly happening with the hub :(

**Comment by gavinpbennett** [comment] 2022-07-10 22:05
@sillyfrog Thanks very much for your efforts with this integration. 

I have been running 2x Pulse 2 hubs (1 upstairs LAN connected, 1 downstairs Wi-Fi connected), and just over 20 battery powered roller blind motors, for about a year. I also notice every so often that devices become unavailable in HA. However, that does not appear to be HA specific, as at the same time, they appear offline in the Pulse 2 iOS app. They do come back online without any interaction. If I need them back asap, I hit a button on the remote, and that seems to wake them up straight away.
I have been noticing the same performance of the battery motors, regardless of Hub firmware version (1.1, 1.2, 1.4). I have automations that open and close all of the 20 odd blinds daily, and maybe once every 3-4 weeks or so, there might be 1 random blind that was missed in an action, which was in an offline state.
I am happy to help with any testing that you want doing.

**Comment by ZoltrixGFC** [comment] 2022-07-11 09:27
I'm also seeing the 3am dropout thing on my HA... but from memory I'm pretty sure the shades report their correct open/close state after it does the dropout thing. Are people here with the issue all using battery? Mine are wired to mains, wondering if that makes a difference? I'll close them tonight and see what happens overnight.

![Screenshot 2022-07-11 192553](https://user-images.githubusercontent.com/77313738/178233249-f601735c-0600-417c-819e-4892455f45ac.png)

**Comment by sillyfrog** [comment] 2022-07-11 11:37
I can confirm that I'm also getting the dropouts at about 3am (just before), but the covers are not moving for me, and the state is correctly reported after the drop out (of <30 seconds). I'll keep monitoring and see if anything changes. I've set one blind to partially open to see if that makes a difference as well.

**Comment by ZoltrixGFC** [comment] 2022-07-12 05:22
Mine did the 3am offline thing again overnight, but afterwards it still reported the correct status (which was closed).
<img width="751" alt="Screenshot 2022-07-12 152219" src="https://user-images.githubusercontent.com/77313738/178414681-1f2dcb9a-a234-445f-9cbf-5d6929a0d056.png">

**Comment by wifihax** [comment] 2022-07-17 10:58
My guess so far is that there is an in-hub process restart of some kind that is responsible for this behaviour. After two issues requiring me to re-pair all blinds with the hub recently I have repaired and brought the hub up relatively isolated (no cloud). I'm still seeing the covers unresponsive at this time so surmise that this isn't initiated through some cloud driven process. The hub works well with this integration without cloud access btw :)

**Comment by colinlandsmeer** [comment] 2022-07-23 02:07
FYI - just noticed a new release coming - which may assist/resolve OP issue (
V1.5.0 (25-JULY-22)
In the latest update, we resolve some issues where Hubs go offline and also may lose shades during an on/off power Cycle.
Remove 3 am Local time Hub Reboot.
New Safe Reboot and power up / power down Logic.
Shade Data backup in event of critical error.
 https://www.automateshades.com/firmware-updates/

**Comment by sillyfrog** [comment] 2022-07-23 02:36
Thanks @colinlandsmeer Good to know, that's a very useful link, and confirms that this is not an issue we can resolve here, so will close this issue.

Annoyingly my hub dropped all it's blinds earlier this week, first time it's ever done it, hopefully this update sorts that out.

**Closed by sillyfrog** 2022-07-23 02:36 UTC

**Comment by ZoltrixGFC** [comment] 2022-07-23 04:15
Sorry is it ok to reply to a closed issue? I was just wondering how the firmware updates work? Is it automated, or do you apply them manually?

**Comment by sumur1au** [comment] 2022-07-23 06:29
You can call support and get them to push the update manually.

**Comment by sumur1au** [comment] 2022-07-24 23:14
I called Acmedia Techsupport in the morning. They were able to manually push the update to my hubs. There is another firmware update coming out in the 2-4 weeks that should be a lot more stable than v1.5.0. v1.5.0 was designed as a quick fix.

**Comment by ZoltrixGFC** [comment] 2022-07-25 01:58
Would they eventually push out the update to everyone? Or you always have to request it manually by calling them?

**Comment by VMaxF1** [comment] 2022-07-30 15:57
I just checked my firmware version through the Android app and it shows v1.5, even though I've never requested that nor done anything to manually update. Hub has been in place for a few months, so definitely would not have been supplied with that version. Therefore some automated update process must be in place!

**Comment by ZoltrixGFC** [comment] 2022-07-31 01:40
Can confirm mine is running 1.5.0 as well.
